jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    fetchDepth: 1
  - task: Npm@1
    displayName: Install Newman
    inputs:
      command: custom
      verbose: false
      customCommand: install newman -g
  - task: Npm@1
    displayName: Install Newman html Reporter
    inputs:
      command: custom
      verbose: false
      customCommand: install -g newman-reporter-htmlextra
  - task: CmdLine@2
    displayName: Check Node & Newman Version
    inputs:
      script: >
        echo Node.js Version:
        node -v
        echo Newman Version:
        newman -v
  - task: CmdLine@2
    displayName: List Directory Contents
    continueOnError: True
    inputs:
      script: dir
  - task: CmdLine@2
    displayName: Run Postman Collection using Neman
    continueOnError: True
    inputs:
      script: newman run Hotel_Booking_Details.postman_collection.json -e Hotel_Booking_Utils.postman_environment.json -r htmlextra --reporters cli,junit,json,htmlextra --reporter-junit-export junitReport.xml --reporter-htmlextra-export report.html
      workingDirectory: $(System.DefaultWorkingDirectory)
  - task: MaciejMaciejewski.postman-report.UploadPostmanHtmlReport.UploadPostmanHtmlReport@1
    displayName: Upload Postman Html Report
    continueOnError: True
  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFiles: ' $(System.DefaultWorkingDirectory)\*.xml '
...
